services:
  postgres:
    image: postgres:16
    container_name: pg-inventory
    environment:
      POSTGRES_USER: invuser
      POSTGRES_PASSWORD: invpass
      POSTGRES_DB: inventorydb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U invuser -d inventorydb"]
      interval: 5s
      timeout: 3s
      retries: 10
